app/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
# =============================================================================
#      FileName: __init__.py
#          Desc: 
#        Author: Houston Wong
#         Email: gzhuangzicheng@corp.netease.com
#      HomePage: http://www.163.com
#       Version: 0.0.1
#    LastChange: 2016-09-04 00:47:53
#       History:
# =============================================================================
'''

from flask import Blueprint

main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
# =============================================================================
#      FileName: views.py
#          Desc: 
#        Author: Houston Wong
#         Email: gzhuangzicheng@corp.netease.com
#      HomePage: http://www.163.com
#       Version: 0.0.1
#    LastChange: 2016-09-04 00:56:30
#       History:
# =============================================================================
'''

from datetime import datetime
from flask import render_template, session, redirect, url_for, request
from . import main
#from .forms import NameForm
#from .. import db
from ..models import Content

@main.route('/', methods=['GET', 'POST'])
def index():
    newslist = Content.query.filter_by(type="news").order_by(Content.timestamp.desc()).limit(5)
    noticelist = Content.query.filter_by(type="notice").order_by(Content.timestamp.desc()).limit(5)
    return render_template('index.html', newslist=newslist, noticelist=noticelist)

@main.route('/intro/basic', methods=['GET'])
def basic():
    return render_template('intro/basic.html')

@main.route('/content/<type>', methods=['GET'])
def contentList(type):
    page = request.args.get('page', 1, type=int)
    pagination = Content.query.filter_by(type=type).order_by(Content.timestamp.desc()).paginate(
        page, per_page=10, error_out=False)
    contents = pagination.items
    return render_template('main/contentList.html', contents=contents, 
            type=type, pagination=pagination)

@main.route('/content/<type>/<int:id>', methods=['GET'])
def contentDisplay(id,type):
    content = Content.query.get_or_404(id)
    if content.addons_uri:
        addons_uri = eval(content.addons_uri)
        return render_template('main/contentDisplay.html',content=content, addons_uri=addons_uri)
    else:
        return render_template('main/contentDisplay.html',content=content)

app/templates/main/contentDisplay.html
{% extends "base.html" %}
{% block title %}TDRW - 欢迎光临{% endblock %}
{% block page_content %} 
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    {% if content.type == "news" %}
                    <li class="active"><a href="{{ url_for('main.contentList',type="news") }}">新闻动态</a></li>
                    {% elif content.type == "notice" %}
                    <li class="active"><a href="{{ url_for('main.contentList',type="notice") }}">通知公告</a></li>
                    {% endif %}
                    <li class="active">详情页</li>
                </ol>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12 well">
            <div class="text-center">
              <h2>{{ content.title }}</h2>
              <footer>{{ moment(content.timestamp).format('lll') }}</footer>
              <br>
            </div>
            
            <div class="col-md-10 col-md-offset-1" >
                <div style="white-space:pre-wrap;WORD-WRAP:break-word;">{{ content.content }}</div>
                {% if addons_uri %}
                <hr>
                <div class="panel panel-default">
                    <div class="panel-heading">附件</div>
                        <div class="panel-body">
                        <ul class="list-unstyled">
                            {% for key, value in addons_uri.iteritems() %}
                            <li><a href="{{value|e}}">{{ key|e}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
          </div>
        </div>
    </div>
{% endblock %}

app/templates/main/contentList.html
{% extends "base.html" %}
{% block title %}TDRW - 通知详情{% endblock %}
{% block page_content %} 
{% import "_paginationmacros.html" as macros %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('main.index') }}">首页</a></li>
                {% if type == "news" %}
                <li class="active">新闻动态</li>
                {% elif type == "notice" %}
                <li class="active">通知公告</li>
                {% endif %}
            </ol>
        </div>
    </div>

    <div class="row">
        <ul class="list-group">
            {% for content in contents %}
            <li class="list-group-item"><a href="{{ url_for('main.contentDisplay', type=type, id=content.id) }}">{{ content.title }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <div class="row text-center">
        <div class="pagination">
             {{ macros.pagination_widget(pagination, 'main.contentList', type=type) }}
        </div>
    </div>

</div>

{% endblock %}

app/templates/main/newsContent.html
{% extends "base.html" %}
{% block title %}TDRW - 欢迎光临{% endblock %}
{% block page_content %} 
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb">
                    <li><a href="#">首页</a></li>
                    <li class="active">新闻动态</li>
                </ol>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12 well">
            <div class="text-center">
              <h2>{{ content.title }}</h2>
              <footer>{{ moment(content.timestamp).format('lll') }}</footer>
              <br>
            </div>
            
            <div class="col-md-10 col-md-offset-1" >
                <div style="white-space:pre-wrap;WORD-WRAP:break-word;">{{ content.content }}</div>
                {% if content.addons_uri %}
                <hr>
                <div class="panel panel-default">
                    <div class="panel-heading">附件</div>
                        <div class="panel-body">
                        <ul class="list-unstyled">
                            {% for (k,v) in eval(content.addons_uri) %}
                            <li><a href="url_for('main.downld')">{{ k,v }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
          </div>
        </div>
    </div>
{% endblock %}